#Requires -Version 5.1
<#
    0verClient - minimal static content server for Windows Server.

    Why this exists:
      On a Windows Server you would normally install IIS and click through Server Manager.
      This script does the same job with zero installation: Windows PowerShell is already
      there, so you just run one command. It serves a folder generated by tools/Publish,
      with HTTP Range support so that resume actually works.

    Usage:
      # 1. copy your published site to C:\0verclient\site first, then:
      .\serve-site.ps1 -Root C:\0verclient\site -Port 8787

      # optional: also open the Windows Firewall port (needs an elevated PowerShell)
      .\serve-site.ps1 -Root C:\0verclient\site -Port 8787 -AddFirewallRule

      # optional: slow the transfer down so the launcher progress bar is visible
      .\serve-site.ps1 -Root C:\0verclient\site -Port 8787 -ThrottleKbps 512

    Remember: the machine firewall is NOT the same as the Tencent Cloud security group.
    You must open the port in BOTH places.

    Notes / limits:
      - Requests are handled one at a time. That is fine for the launcher (it downloads
        one file at a time) and for the small test pack. For real games with many players,
        use IIS or nginx instead.
      - Keep this file pure ASCII: Windows PowerShell 5.1 decodes BOM-less .ps1 files using
        the ANSI code page, and non-ASCII text breaks the parser.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Root,
    [int]$Port = 8787,
    [int]$ThrottleKbps = 0,
    [string]$Bind = '0.0.0.0',
    [int]$HeaderTimeoutMs = 2000,
    [switch]$AddFirewallRule
)

$ErrorActionPreference = 'Stop'

$rootFull = [System.IO.Path]::GetFullPath($Root).TrimEnd('\')
if (-not (Test-Path -LiteralPath $rootFull -PathType Container)) {
    Write-Host "ERROR: root folder not found: $rootFull" -ForegroundColor Red
    exit 1
}
if (-not (Test-Path -LiteralPath (Join-Path $rootFull 'index.json') -PathType Leaf)) {
    Write-Host "WARNING: index.json is not in $rootFull" -ForegroundColor Yellow
    Write-Host "         Copy the CONTENTS of the published site folder here (index.json must be at the root)." -ForegroundColor Yellow
}

if ($AddFirewallRule) {
    try {
        New-NetFirewallRule -DisplayName "0verClient content $Port" -Direction Inbound `
            -Protocol TCP -LocalPort $Port -Action Allow -ErrorAction Stop | Out-Null
        Write-Host "Windows Firewall: inbound TCP $Port allowed." -ForegroundColor Green
    }
    catch {
        Write-Host "Windows Firewall: could not add the rule ($($_.Exception.Message))" -ForegroundColor Yellow
        Write-Host "Run PowerShell as Administrator, or add the rule by hand." -ForegroundColor Yellow
    }
}

$contentTypes = @{
    '.json' = 'application/json; charset=utf-8'
    '.txt'  = 'text/plain; charset=utf-8'
    '.md'   = 'text/plain; charset=utf-8'
    '.html' = 'text/html; charset=utf-8'
    '.htm'  = 'text/html; charset=utf-8'
    '.png'  = 'image/png'
    '.jpg'  = 'image/jpeg'
    '.zip'  = 'application/zip'
}

function Get-ContentType([string]$path) {
    $ext = [System.IO.Path]::GetExtension($path).ToLowerInvariant()
    if ($contentTypes.ContainsKey($ext)) { return $contentTypes[$ext] }
    return 'application/octet-stream'
}

function Send-Text($stream, [int]$status, [string]$reason, [string]$body) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($body)
    $header = "HTTP/1.1 $status $reason`r`nContent-Type: text/plain; charset=utf-8`r`nContent-Length: $($bytes.Length)`r`nConnection: close`r`n`r`n"
    $hb = [System.Text.Encoding]::ASCII.GetBytes($header)
    $stream.Write($hb, 0, $hb.Length)
    $stream.Write($bytes, 0, $bytes.Length)
    $stream.Flush()
}

function Get-RequestHeader($stream) {
    $sb = New-Object System.Text.StringBuilder
    $one = New-Object byte[] 1

    while ($sb.Length -lt 16384) {
        try {
            $n = $stream.Read($one, 0, 1)
        }
        catch {
            # ReceiveTimeout expired: the client connected but never sent a single byte.
            #
            # This is not a rare case. Browsers and HTTP clients routinely open a
            # speculative connection and only later decide whether to send a request.
            # Without a timeout here, the single-threaded accept loop blocks on that one
            # idle connection FOREVER: the port still shows LISTENING and the process is
            # still alive, but nobody gets served any more - not even the server itself
            # asking 127.0.0.1. That is the most deceptive kind of "the service is down".
            Write-Host "  [timeout] connection opened but no request arrived - closing it" -ForegroundColor DarkYellow
            return $null
        }

        if ($n -le 0) { return $null }
        [void]$sb.Append([char]$one[0])

        if ($sb.Length -ge 4 -and
            $sb[$sb.Length - 4] -eq "`r" -and $sb[$sb.Length - 3] -eq "`n" -and
            $sb[$sb.Length - 2] -eq "`r" -and $sb[$sb.Length - 1] -eq "`n") {
            break
        }
    }

    return $sb.ToString()
}

function Handle-Client($client) {
    # This timeout is the defence line: without it a single idle connection stops the
    # whole content source from serving anybody (see the catch in Get-RequestHeader).
    $client.ReceiveTimeout = $HeaderTimeoutMs
    $client.SendTimeout = 20000

    $stream = $client.GetStream()
    $client.NoDelay = $true

    $raw = Get-RequestHeader $stream
    if ([string]::IsNullOrEmpty($raw)) { return }

    $lines = @($raw -split "`r`n" | Where-Object { $_ -ne '' })
    if ($lines.Count -eq 0) { return }

    $parts = $lines[0] -split ' '
    if ($parts.Count -lt 2) { return }

    $method = $parts[0].ToUpperInvariant()
    $target = $parts[1]

    $headers = @{}
    for ($i = 1; $i -lt $lines.Count; $i++) {
        $colon = $lines[$i].IndexOf(':')
        if ($colon -gt 0) {
            $key = $lines[$i].Substring(0, $colon).Trim().ToLowerInvariant()
            $headers[$key] = $lines[$i].Substring($colon + 1).Trim()
        }
    }

    if ($method -ne 'GET' -and $method -ne 'HEAD') {
        Send-Text $stream 405 'Method Not Allowed' 'Only GET/HEAD are supported.'
        Write-Host "  405 $method $target"
        return
    }

    $path = [System.Uri]::UnescapeDataString(($target -split '\?')[0])
    $relative = $path.TrimStart('/')
    if ([string]::IsNullOrEmpty($relative)) { $relative = 'index.json' }
    $relative = $relative -replace '/', '\'

    # Same path guard the launcher uses: refuse traversal, absolute paths and drive letters.
    # Only a segment that is exactly ".." is rejected, so names like "a..b.txt" still work.
    if ($relative -match '(^|\\)\.\.(\\|$)' -or [System.IO.Path]::IsPathRooted($relative) -or $relative -match ':') {
        Send-Text $stream 400 'Bad Request' 'Path not allowed.'
        Write-Host "  400 rejected path: $relative" -ForegroundColor Yellow
        return
    }

    $full = [System.IO.Path]::GetFullPath((Join-Path $rootFull $relative))
    if (-not $full.StartsWith($rootFull + '\', [System.StringComparison]::OrdinalIgnoreCase)) {
        Send-Text $stream 400 'Bad Request' 'Path escapes the site root.'
        Write-Host "  400 escape attempt: $relative" -ForegroundColor Yellow
        return
    }

    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
        Send-Text $stream 404 'Not Found' 'Not found.'
        Write-Host "  404 $relative"
        return
    }

    $item = Get-Item -LiteralPath $full
    $totalLength = $item.Length

    $start = [int64]0
    $end = [int64]($totalLength - 1)
    $partial = $false

    if ($headers.ContainsKey('range')) {
        $rangeValue = $headers['range']
        if ($rangeValue.StartsWith('bytes=')) {
            $spec = ($rangeValue.Substring(6) -split ',')[0].Trim()
            $dash = $spec.IndexOf('-')
            if ($dash -ge 0) {
                $startText = $spec.Substring(0, $dash)
                $endText = $spec.Substring($dash + 1)
                if ($startText -match '^\d+$') {
                    $start = [int64]$startText
                    $partial = $true
                }
                if ($endText -match '^\d+$') {
                    $candidate = [int64]$endText
                    if ($candidate -lt $end) { $end = $candidate }
                }
            }
        }
    }

    if ($start -ge $totalLength -and $totalLength -gt 0) {
        $header = "HTTP/1.1 416 Range Not Satisfiable`r`nContent-Range: bytes */$totalLength`r`nConnection: close`r`n`r`n"
        $hb = [System.Text.Encoding]::ASCII.GetBytes($header)
        $stream.Write($hb, 0, $hb.Length)
        $stream.Flush()
        Write-Host "  416 $relative"
        return
    }

    $length = $end - $start + 1

    $sb = New-Object System.Text.StringBuilder
    if ($partial) { [void]$sb.Append("HTTP/1.1 206 Partial Content`r`n") } else { [void]$sb.Append("HTTP/1.1 200 OK`r`n") }
    [void]$sb.Append("Content-Type: $(Get-ContentType $full)`r`n")
    [void]$sb.Append("Accept-Ranges: bytes`r`n")
    [void]$sb.Append("Content-Length: $length`r`n")
    if ($partial) { [void]$sb.Append("Content-Range: bytes $start-$end/$totalLength`r`n") }
    [void]$sb.Append("Connection: close`r`n`r`n")

    $hb = [System.Text.Encoding]::ASCII.GetBytes($sb.ToString())
    $stream.Write($hb, 0, $hb.Length)

    if ($partial) {
        Write-Host "  206 $relative (from byte $start)" -ForegroundColor Cyan
    }
    else {
        Write-Host "  200 $relative ($totalLength bytes)"
    }

    if ($method -eq 'HEAD') {
        $stream.Flush()
        return
    }

    $file = [System.IO.File]::Open($full, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::Read)
    try {
        [void]$file.Seek($start, [System.IO.SeekOrigin]::Begin)

        $buffer = New-Object byte[] 65536
        $remaining = [int64]$length
        $sent = [int64]0
        $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

        while ($remaining -gt 0) {
            $want = [int][Math]::Min([int64]$buffer.Length, $remaining)
            $read = $file.Read($buffer, 0, $want)
            if ($read -le 0) { break }

            $stream.Write($buffer, 0, $read)
            $remaining -= $read
            $sent += $read

            if ($ThrottleKbps -gt 0) {
                $expected = $sent / ($ThrottleKbps * 1024.0)
                $actual = $stopwatch.Elapsed.TotalSeconds
                if ($expected -gt $actual) {
                    Start-Sleep -Milliseconds ([int](($expected - $actual) * 1000))
                }
            }
        }

        $stream.Flush()
    }
    finally {
        $file.Close()
    }
}

$bindAddress = [System.Net.IPAddress]::Any
if ($Bind -ne '0.0.0.0' -and $Bind -ne '*') {
    try {
        $bindAddress = [System.Net.IPAddress]::Parse($Bind)
    }
    catch {
        Write-Host "ERROR: -Bind '$Bind' is not a valid IP address. Use 0.0.0.0 or 127.0.0.1." -ForegroundColor Red
        exit 1
    }
}

$listener = [System.Net.Sockets.TcpListener]::new($bindAddress, $Port)

try {
    $listener.Start()
}
catch {
    Write-Host "ERROR: could not listen on port $Port" -ForegroundColor Red
    Write-Host "       detail: $($_.Exception.Message)" -ForegroundColor DarkGray
    Write-Host ''
    Write-Host 'Something is already using that port. By far the most common cause is that an' -ForegroundColor Yellow
    Write-Host 'OLDER COPY OF THIS SAME SCRIPT is still running - an old instance must be stopped' -ForegroundColor Yellow
    Write-Host 'before a new one can bind the port.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host '  1) find the owner:'
    Write-Host "       netstat -ano | findstr :$Port"
    Write-Host '     (the pid is the number in the last column, with LISTENING next to it)'
    Write-Host ''
    Write-Host '  2) kill it:'
    Write-Host '       Stop-Process -Id <PID> -Force'
    Write-Host ''
    Write-Host '  Then run this script again.'
    Write-Host ''
    Write-Host "Do NOT just switch ports. The port is baked into the launcher's settings AND into" -ForegroundColor Yellow
    Write-Host 'the absolute file URLs of the published manifest. Moving to 8788 would also require:' -ForegroundColor Yellow
    Write-Host '     .\publish-testpack.ps1 -Port 8788     (on your PC)' -ForegroundColor Yellow
    Write-Host '     re-copying build\site to the server, and changing the index url in Settings.' -ForegroundColor Yellow
    exit 1
}

Write-Host ""
Write-Host "0verClient content server is running" -ForegroundColor Green
Write-Host "  root        : $rootFull"
Write-Host "  listening   : $Bind`:$Port$(if ($Bind -eq '0.0.0.0') { ' (all network interfaces)' } else { ' (this machine only)' })"
Write-Host "  throttle    : $(if ($ThrottleKbps -gt 0) { "$ThrottleKbps KB/s" } else { 'off' })"
Write-Host "  idle timeout: $HeaderTimeoutMs ms (a connection that sends no request is dropped)"
Write-Host "  requests    : one at a time. A browser preconnect can delay the next request by up"
Write-Host "                to the idle timeout. Fine for the launcher; use IIS for many players."
Write-Host ""
Write-Host "  Local test  : http://127.0.0.1:$Port/index.json"
if ($bindAddress.Equals([System.Net.IPAddress]::Any)) {
    Write-Host "  From outside: http://<this machine's public IP>:$Port/index.json"
}
else {
    Write-Host '  (bound to loopback: reachable from this machine only)'
}
Write-Host ""
Write-Host "Press Ctrl+C to stop." -ForegroundColor DarkGray
Write-Host ""

try {
    while ($true) {
        $client = $listener.AcceptTcpClient()
        try {
            Handle-Client $client
        }
        catch {
            Write-Host "  ERR $($_.Exception.Message)" -ForegroundColor Red
        }
        finally {
            $client.Close()
        }
    }
}
finally {
    $listener.Stop()
}
