<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OverClient.Publish</RootNamespace>
    <AssemblyName>Publish</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\0verClient.Core\0verClient.Core.csproj" />
  </ItemGroup>

</Project>
