<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>OverClient.App</RootNamespace>
    <AssemblyName>0verClient</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\0verClient.Core\0verClient.Core.csproj" />
  </ItemGroup>

</Project>
